In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot

In [53]:
company = pd.read_csv("C:/Users/SUSHIL/Downloads/Company_Data (1).csv")

In [54]:
company

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0     9.50        138      73           11         276    120       Bad   42   
1    11.22        111      48           16         260     83      Good   65   
2    10.06        113      35           10         269     80    Medium   59   
3     7.40        117     100            4         466     97    Medium   55   
4     4.15        141      64            3         340    128       Bad   38   
..     ...        ...     ...          ...         ...    ...       ...  ...   
395  12.57        138     108           17         203    128      Good   33   
396   6.14        139      23            3          37    120    Medium   55   
397   7.41        162      26           12         368    159    Medium   40   
398   5.94        100      79            7         284     95       Bad   50   
399   9.71        134      37            0          27    120      Good   49   

     Education Urban   US  
0           17   Yes  Yes  
1           10   Yes  Yes  
2           12   Yes  Yes  
3           14   Yes  Yes  
4           13   Yes   No  
..         ...   ...  ...  
395         14   Yes  Yes  
396         11    No  Yes  
397         18   Yes  Yes  
398         12   Yes  Yes  
399         16   Yes  Yes  

[400 rows x 11 columns]

In [55]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
for column_name in company.columns:
    if company[column_name].dtype == object:
        company[column_name] = le.fit_transform(company[column_name])
    else:
        pass

In [56]:
features = company.iloc[:,0:10]
labels = company.iloc[:,10]

In [57]:
colnames = list(company.columns)
predictors = colnames[0:10]
target = colnames[10]

In [58]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(features,labels,test_size = 0.2,stratify = labels)

In [59]:
from sklearn.ensemble import RandomForestClassifier as RF
model = RF(n_jobs = 3,n_estimators = 15, oob_score = True, criterion = "entropy")
model.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=15, n_jobs=3,
                       oob_score=True)

In [60]:
model.estimators_
model.classes_
model.n_features_
model.n_classes_

2

In [61]:
model.n_features_

10

In [62]:

model.classes_

array([0, 1])

In [63]:
model.n_outputs_


1

In [64]:
model.oob_score_

0.83125

In [65]:
prediction = model.predict(x_train)

In [66]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_train,prediction)

In [67]:
accuracy

0.996875

In [68]:
np.mean(prediction == y_train)

0.996875

In [69]:
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_train,prediction)

In [70]:
confusion

array([[114,   0],
       [  1, 205]], dtype=int64)

In [71]:
pred_test = model.predict(x_test)

In [72]:
pred_test

array([1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1])

In [73]:
acc_test =accuracy_score(y_test,pred_test)

In [74]:
acc_test

0.9375

In [75]:
from sklearn.tree import export_graphviz
import six
import sys
sys.modules['sklearn.externals.six'] = six
import pydotplus
from sklearn.externals.six import StringIO

In [76]:
tree = model.estimators_[5]

In [77]:
tree

DecisionTreeClassifier(criterion='entropy', max_features='auto',
                       random_state=918306864)

In [78]:
dot_data = StringIO()
export_graphviz(tree,out_file = dot_data, filled = True,rounded = True, feature_names = predictors ,class_names = target,impurity =False)

In [79]:
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())

In [80]:
graph.write_pdf('companyrf.pdf')

True

In [81]:
graph.write_png('companyrf.png')

True